name: Container

on:
  pull_request:
  push:
    branches: [main, master]

permissions:
  contents: read

jobs:
  container:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - run: docker compose config
      - run: docker build .
